[build.environment]
  NODE_VERSION = "14"
  PLAYWRIGHT_BROWSERS_PATH = "0"

[build]
  publish = "dist"
  command = "npx playwright install-deps && npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
